#' Get a set of equally spaced hues values
#'
#' @description
#' Rotates around the 360 degrees of hue on the HCL colour wheel,
#'
#' Starts at `start` and rotates `cycles` times around the wheel to obtain `n`
#' colours at equal intervals
#'
#' @param n number of hues to return
#' @param start starting hue value, in degrees from 0 to 359
#' @param cycles number of cycles rotating around the
#'
#' @return vector
#' @export
#'
#' @examples
#' hueSet()
#'
#' hueSet(cycles = 1)
#'
#' hueSet(start = 0, cycles = 1)
#'
#' hueSet(start = 0, n = 9, cycles = 3)
hueSet <- function(n = 10, start = 180, cycles = 2) {
  if (start > 360 || start < 0) stop("start must be between 0 and 360")
  if (n %% cycles != 0) stop("n must be divisible by cycles")
  cycleSize <- n / cycles
  cycleShift <- 360 / n
  # for each cycle get n/cycles hue values
  # shift start and end forward by 360/n degrees each cycle
  # step size within the cycle is calculated by seq to return desired cycleSize
  hues <- lapply(
    X = seq_len(cycles) - 1,
    FUN = function(cycleIndex) {
      hueSet <- seq(
        from = start + cycleIndex * cycleShift,
        to = start + (360 - cycleShift * (cycles - cycleIndex)),
        length.out = cycleSize
      )
      return(hueSet)
    }
  )
  # combine hue values in order generated by all cycles
  hues <- unlist(hues)
  # ensure values wrap around within 0 to <360 degrees
  hues <- dplyr::if_else(hues >= 360, hues - 360, hues)
  return(hues)
}

